id: sysprefs_system_wide_preferences_configure
title: Require Administrator Password to Modify System-Wide Preferences
discussion: "The system _MUST_ be configured to require an administrator password in order to modify the system-wide preferences in System Preferences. \n\nSome Preference Panes in System Preferences contain settings that affect the entire system. Requiring a password to unlock these system-wide settings reduces the risk of a non-authorized user modifying system configurations.\n"
check: |
  /usr/bin/security authorizationdb read system.preferences 2> /dev/null |  /usr/bin/grep -A 1 "<key>shared</key>" | /usr/bin/grep -c "<false/>"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/security authorizationdb read system.preferences > /tmp/system.preferences.plist
  key_value=$(/usr/libexec/PlistBuddy -c "Print :shared" /tmp/system.preferences.plist 2>&1)
  if [[ "$key_value" == *"Does Not Exist"* ]]; then
    /usr/libexec/PlistBuddy -c "Add :shared bool false" /tmp/system.preferences.plist
  else
    /usr/libexec/PlistBuddy -c "Set :shared false" /tmp/system.preferences.plist
  fi
  /usr/bin/security authorizationdb write system.preferences < /tmp/system.preferences.plist
  ----
references:
  cce:
    - $OS_VALUE
  800-53r5:
    - AC-6
    - AC-6(2)
    - AC-6(1)
  800-53r4:
    - AC-6
    - AC-6(1)
    - AC-6(2)
  disa_stig:
    - $OS_VALUE
  srg:
    - $OS_VALUE
  cci:
    - CCI-001958
  800-171r2:
    - 3.1.5
    - 3.1.6
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - stig
  - cis_lvl1
  - cis_lvl2
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85389-5
        disa_stig:
          - APPL-11-002069
        srg:
          - SRG-OS-000378-GPOS-00163
        cis:
          benchmark:
            - 2.5.9 (level 1)
          controls v8:
            - 4.1
    '12.0':
      references:
        cce:
          - CCE-91079-4
        disa_stig:
          - APPL-12-002069
        srg:
          - None
        cis:
          benchmark:
            - 2.5.9 (level 1)
          controls v8:
            - 4.1
