id: os_config_data_install_enforce
title: $OS_VALUE
discussion: $OS_VALUE
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
  .objectForKey('ConfigDataInstall').js
  EOS
result: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - SI-3
      - SI-2(5)
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - stig
mobileconfig: true
mobileconfig_info:
  com.apple.SoftwareUpdate:
    ConfigDataInstall: true
os_specifics:
  macOS:
    '11.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-85466-1
        cis:
          benchmark:
            - 1.5 (level 1)
          controls v8:
            - 10.1
            - 10.2
            - 10.4
      discussion: |
        Software Update _MUST_ be configured to update XProtect, MRT, and Gatekeepr automatically.

        This setting enforces definition updates for XProtect, MRT, and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.

        link:https://support.apple.com/en-us/HT207005[]

        NOTE: Software update will automatically update XProtect, MRT, and Gatekeeper by default in the macOS.
      title: Enforce Installation of XProtect, MRT, and Gatekeeper Updates Automatically
    '10.15':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-84929-9
        cis:
          benchmark:
            - N/A
          controls v8:
            - 10.1
            - 10.2
            - 10.4
      discussion: |
        Software Update _MUST_ be configured to update XProtect, MRT, and Gatekeepr automatically.

        This setting enforces definition updates for XProtect, MRT, and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.

        link:https://support.apple.com/en-us/HT207005[]

        NOTE: Software update will automatically update XProtect, MRT, and Gatekeeper by default in the macOS.
      title: Enforce Installation of XProtect, MRT, and Gatekeeper Updates Automatically
    '12.0':
      references:
        disa:
          disa_stig:
            - APPL-12-002070
          srg:
            - SRG-OS-000480-GPOS-00227
          sfr:
            - N/A
        nist:
          cce:
            - CCE-90913-5
        cis:
          benchmark:
            - 1.5 (level 1)
          controls v8:
            - 10.1
            - 10.2
            - 10.4
      discussion: |
        Software Update _MUST_ be configured to update XProtect, MRT, and Gatekeepr automatically.

        This setting enforces definition updates for XProtect and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.

        link:https://support.apple.com/en-us/HT207005[]

        NOTE: Software update will automatically update XProtect and Gatekeeper by default in the macOS.
      title: Enforce Installation of XProtect and Gatekeeper Updates Automatically
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91774-0
        cis:
          benchmark:
            - 1.6 (level 1)
          controls v8:
            - 7.3
            - 7.4
            - 7.7
      discussion: |
        Software Update _MUST_ be configured to update XProtect Remediator and Gatekeepr automatically.

        This setting enforces definition updates for XProtect Remediator and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.

        link:https://support.apple.com/en-us/HT207005[]

        NOTE: Software update will automatically update XProtect Remediator and Gatekeeper by default in the macOS.
      title: Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically
