id: os_config_profile_ui_install_disable
title: Disable Installation of Configuration Profiles through the User Interface
discussion: |
  Installation of configuration profiles through the user interface _MUST_ be disabled and only be permitted through an authorized MDM server.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowUIConfigurationProfileInstallation').js
  EOS
result: 'false'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-5
    800-171r2:
      - 3.4.5
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUIConfigurationProfileInstallation: false
os_specifics:
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - None
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91775-7
        cis:
          benchmark:
            - N/A
          controls v8:
            - N/A
