id: os_directory_services_configured
title: Integrate System into a Directory Services Infrastructure
discussion: "The macOS system _MUST_ be integrated into a directory services infrastructure. \n\nA directory service infrastructure enables centralized user and rights management, as well as centralized control over computer and user configurations. Integrating the macOS systems used throughout an organization into a directory services infrastructure ensures more administrator oversight and security than allowing distinct user account databases to exist on each separate system.\n"
check: $OS_VALUE
result: 0
fix: |
  Integrate the system into an existing directory services infrastructure.
references:
  disa:
    cci:
      - CCI-000366
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - CM-6(b)
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cisv8
  - stig
severity: high
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    11.0:
      references:
        disa:
          disa_stig:
            - APPL-11-000016
          srg:
            - SRG-OS-000480-GPOS-00227
          sfr:
            - N/A
        nist:
          cce:
            - CCE-85494-3
        cis:
          benchmark:
            - N/A
          controls v8:
            - 6.7
      check: |
        /usr/bin/dscl localhost -list . | /usr/bin/grep -vE '(Contact|Search|Local|^$)'; /bin/echo $?
    '10.15':
      references:
        disa:
          disa_stig:
            - AOSX-15-000016
          srg:
            - SRG-OS-000480-GPOS-00227
          sfr:
            - N/A
        nist:
          cce:
            - CCE-84951-3
        cis:
          benchmark:
            - N/A
          controls v8:
            - 6.7
      check: |
        /usr/bin/dscl localhost -list . | /usr/bin/grep -vE '(Contact|Search|Local|^$)'; /bin/echo $?
    '12.0':
      references:
        disa:
          disa_stig:
            - APPL-12-000016
          srg:
            - SRG-OS-000480-GPOS-00227
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91087-7
        cis:
          benchmark:
            - N/A
          controls v8:
            - 6.7
      check: |
        /usr/bin/dscl localhost -list . | /usr/bin/grep -qvE '(Contact|Search|Local|^$)'; /bin/echo $?
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91778-1
        cis:
          benchmark:
            - N/A
          controls v8:
            - 6.7
      check: |
        /usr/bin/dscl localhost -list . | /usr/bin/grep -qvE '(Contact|Search|Local|^$)'; /bin/echo $?
