id: os_erase_content_and_settings_disable
title: Disable Erase Content and Settings
discussion: |
  Erase Content and Settings _MUST_ be disabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowEraseContentAndSettings').js
  EOS
result: 'false'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - CCI-000381
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-7
      - CM-7(1)
    800-53r4:
      - CM-7
      - CM-7(1)
tags:
  - none
  - stig
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowEraseContentAndSettings: false
os_specifics:
  macOS:
    '12.0':
      references:
        disa:
          disa_stig:
            - APPL-12-005061
          srg:
            - SRG-OS-000095-GPOS-00049
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91103-2
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91783-1
