id: os_erase_contents_and_settings_disable
title: Ensure Allow Erase All Content and Settings is set to Disabled
discussion: |
  Erase all contents and settings _MUST_ be disabled on institutionally owned iOS devices.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-6
      - CM-7
      - CM-7(1)
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
severity: ''
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowEraseContentAndSettings: false
os_specifics:
  iOS:
    '16.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - N/A
        cis:
          benchmark:
            - 3.2.1.12 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 4.1
