id: os_install_configuration_profile_disable
title: Ensure Allow Installing Configuration Profiles is Set to Disabled
discussion: |
  Configuration profiles _MUST_ be installed via an organization's MDM.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-6
      - CM-7
      - CM-7(1)
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
  - 800-53r5
severity: ''
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUIConfigurationProfileInstallation: false
os_specifics:
  iOS:
    '16.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - N/A
        cis:
          benchmark:
            - 3.2.1.15 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 4.1
