id: os_install_configuration_profile_disable
title: Ensure Allow Installing Configuration Profiles is Set to Disabled
discussion: |
  Configuration profiles _MUST_ be installed via an organization's MDM.
references:
  nist:
    cce:
      ios_26:
        - CCE-95484-2
      ios_18:
        - CCE-94444-7
      ios_17:
        - CCE-93429-9
      visionos_26:
        - CCE-95581-5
    800-53r5:
      - CM-6
      - CM-7
      - CM-7(1)
  disa:
    disa_stig:
      ios_18:
        - AIOS-18-015500
  cis:
    benchmark:
      ios_26:
        - 3.2.1.15 (level 1 - Institutionally-Owned Devices)
      ios_18:
        - 3.2.1.15 (level 1 - Institutionally-Owned Devices)
      ios_17:
        - 3.2.1.15 (level 1 - Institutionally-Owned Devices)
    controls_v8:
      - 4.1
  bsi:
    indigo:
      ios_17:
        - ANNEX D (Section 5.6.1 - Mail)
platforms:
  iOS:
    '26.0':
      supervised: true
      benchmarks:
        - name: cis_lvl1_enterprise
        - name: cis_lvl2_enterprise
    '18.0':
      supervised: true
      benchmarks:
        - name: cis_lvl1_enterprise
        - name: cis_lvl2_enterprise
        - name: ios_stig
          severity: medium
        - name: indigo_base
          severity: medium
        - name: indigo_high
          severity: medium
    '17.0':
      supervised: true
      benchmarks:
        - name: cis_lvl1_enterprise
        - name: cis_lvl2_enterprise
        - name: indigo_base
        - name: indigo_high
    introduced: '6.0'
  visionOS:
    '26.0':
      supervised: true
    introduced: '2.0'
tags:
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
mobileconfig_info:
  - PayloadType: com.apple.applicationaccess
    PayloadContent:
      - allowUIConfigurationProfileInstallation: false
