id: os_modify_cellular_data_app_settings_disable
title: Ensure Allow modifying cellular data app settings is set to Disabled
discussion: |
  The ability to modify cellular data app settings _MUST_ be disabled.
references:
  nist:
    cce:
      ios_26:
        - CCE-95496-6
      ios_18:
        - CCE-94450-4
      ios_17:
        - CCE-93434-9
    800-53r5:
      - CM-7
      - CM-7(1)
  cis:
    benchmark:
      ios_26:
        - 3.2.1.18 (level 2 - Institutionally-Owned Devices)
      ios_18:
        - 3.2.1.18 (level 2 - Institutionally-Owned Devices)
      ios_17:
        - 3.2.1.18 (level 2 - Institutionally-Owned Devices)
    controls_v8:
      - 4.1
platforms:
  iOS:
    '26.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
    '18.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
    '17.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
    introduced: '7.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
mobileconfig_info:
  - PayloadType: com.apple.applicationaccess
    PayloadContent:
      - allowAppCellularDataModification: false
