id: os_newsyslog_files_owner_group_configure
title: Configure System Log Files Owned by Root and Group to Wheel
discussion: |
  The system log files _MUST_ be owned by root.

  System logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
check: |
  /usr/bin/stat -f '%Su:%Sg:%N' $(/usr/bin/grep -v '^#' /etc/newsyslog.conf | /usr/bin/awk '{ print $1 }') 2> /dev/null | /usr/bin/awk '!/^root:wheel:/{print $1}' | /usr/bin/wc -l | /usr/bin/tr -d ' '
result: 0
fix: "[source,bash]\n----\n/usr/sbin/chown root:wheel $(/usr/bin/stat -f '%Su:%Sg:%N' $(/usr/bin/grep -v '^#' /etc/newsyslog.conf | /usr/bin/awk '{ print $1 }') 2> /dev/null | /usr/bin/awk -F\":\" '!/^root:wheel:/{print $3}')\n----  \n"
references:
  disa:
    cci:
      - CCI-001314
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - SI-11
    800-53r4:
      - SI-11
    800-171r2:
      - N/A
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - stig
  - manual
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85469-5
        disa_stig:
          - APPL-11-004001
        srg:
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
    '10.15':
      references:
        cce:
          - CCE-84942-2
        disa_stig:
          - AOSX-15-004001
        srg:
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
    '12.0':
      references:
        cce:
          - CCE-90954-9
        disa_stig:
          - APPL-12-004001
        srg:
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
    '13.0':
      references:
        cce:
          - CCE-91825-0
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
