id: os_pairing_non_configurator_hosts_disable
title: Ensure Allow pairing with non-Configurator hosts is set to Disabled
discussion: |
  Host pairing with a non-Configurator host _MUST_ be disabled.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-6
      - CM-7
      - CM-7(1)
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl2_enterprise
  - cisv8
severity: ''
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowHostPairing: false
os_specifics:
  iOS:
    '16.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - N/A
        cis:
          benchmark:
            - 3.2.1.20 (level 2 - Institutionally-Owned Devices)
          controls v8:
            - 4.8
