id: os_pairing_non_configurator_hosts_disable
title: Ensure Allow pairing with non-Configurator hosts is set to Disabled
discussion: |
  Host pairing with a non-Configurator host _MUST_ be disabled.
references:
  nist:
    cce:
      ios_26:
        - CCE-95503-9
      ios_18:
        - CCE-94454-6
      ios_17:
        - CCE-93438-0
    800-53r5:
      - CM-6
      - CM-7
      - CM-7(1)
  disa:
    cci:
      - CCI-000366
    disa_stig:
      ios_18:
        - AIOS-18-016500
    sfr:
      - 'FMT_MOF_EXT.1.2 #47'
  cis:
    benchmark:
      ios_26:
        - 3.2.1.20 (level 2 - Institutionally-Owned Devices)
      ios_18:
        - 3.2.1.20 (level 2 - Institutionally-Owned Devices)
      ios_17:
        - 3.2.1.20 (level 2 - Institutionally-Owned Devices)
    controls_v8:
      - 4.8
  bsi:
    indigo:
      ios_17:
        - ANNEX K
platforms:
  iOS:
    '26.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
    '18.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
        - name: ios_stig
        - name: indigo_base
        - name: indigo_high
    '17.0':
      supervised: true
      benchmarks:
        - name: cis_lvl2_enterprise
        - name: indigo_base
        - name: indigo_high
    introduced: '7.0'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
mobileconfig_info:
  - PayloadType: com.apple.applicationaccess
    PayloadContent:
      - allowHostPairing: false
