id: os_sshd_client_alive_count_max_configure
title: $OS_VALUE
discussion: $OS_VALUE
check: $OS_VALUE
result:
  integer: 1
fix: $OS_VALUE
references:
  disa:
    cci:
      - CCI-001133
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - SC-10
    800-53r4:
      - SC-10
    800-171r2:
      - 3.13.9
    cce:
      - $OS_VALUE
odv:
  hint: Number of seconds.
  recommended: 0
  stig: 0
tags:
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85456-2
        disa_stig:
          - APPL-11-000052
        srg:
          - SRG-OS-000163-GPOS-00072
      discussion: |
        If SSHD is enabled it _MUST_ be configured with an Active Client Alive Maximum Count set to $ODV. Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session or an incomplete login attempt will also free up resources committed by the managed network element.

        NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
      title: Set SSHD Active Client Alive Maximum to $ODV
      check: |
        /usr/bin/grep -c "^ClientAliveCountMax $ODV" /etc/ssh/sshd_config
      fix: |
        [source,bash]
        ----
        /usr/bin/sed -i.bak 's/.*ClientAliveCountMax.*/ClientAliveCountMax $ODV/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
        ----
    '12.0':
      references:
        cce:
          - CCE-91007-5
        disa_stig:
          - APPL-12-000052
        srg:
          - SRG-OS-000163-GPOS-00072
      discussion: |
        If SSHD is enabled it _MUST_ be configured with the Client Alive Maximum Count set to $ODV.

        This will set the number of client alive messages which may be sent without the SSH server receiving any messages back from the client.  If this threshold is reached while client alive messages are being sent, the SSH server will disconnect the client, terminating the session.  The client alive messages are sent through the encrypted channel and therefore will not be spoofable.  The client alive mechanism is valuable when the client or server depend on knowing when a connection has become unresponsive.

        NOTE: This setting is not intended to manage idle user sessions where there is no input from the client. Its purpose is to monitor for interruptions in network connectivity and force the session to terminate after the connection appears to be broken.

        NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
      title: Configure SSHD ClientAliveCountMax to $ODV
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/clientalivecountmax/{print $2}'
      fix: |
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        echo "clientalivecountmax $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
    '13.0':
      references:
        cce:
          - CCE-91886-2
        disa_stig:
          - N/A
        srg:
          - N/A
      discussion: |
        If SSHD is enabled it _MUST_ be configured with the Client Alive Maximum Count set to $ODV.

        This will set the number of client alive messages which may be sent without the SSH server receiving any messages back from the client.  If this threshold is reached while client alive messages are being sent, the SSH server will disconnect the client, terminating the session.  The client alive messages are sent through the encrypted channel and therefore will not be spoofable.  The client alive mechanism is valuable when the client or server depend on knowing when a connection has become unresponsive.

        NOTE: This setting is not intended to manage idle user sessions where there is no input from the client. Its purpose is to monitor for interruptions in network connectivity and force the session to terminate after the connection appears to be broken.

        NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
      title: Configure SSHD ClientAliveCountMax to $ODV
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/clientalivecountmax/{print $2}'
      fix: |
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        echo "clientalivecountmax $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
