id: os_sshd_permit_root_login_configure
title: Disable Root Login for SSH
discussion: "If SSH is enabled to assure individual accountability and prevent unauthorized access, logging in as root via SSH _MUST_ be disabled. \n\nThe macOS system MUST  require individuals to be authenticated with an individual authenticator prior to using a group authenticator, and administrator users _MUST_ never log in directly as root. \n\nNOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.\n"
check: $OS_VALUE
result:
  integer: 1
fix: $OS_VALUE
references:
  cce:
    - $OS_VALUE
  cci:
    - CCI-000770
  800-53r5:
    - IA-2(5)
  800-53r4:
    - IA-2(5)
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
tags:
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85385-3
        disa_stig:
          - APPL-11-001100
        srg:
          - SRG-OS-000109-GPOS-00056
      check: |
        /usr/bin/grep -c "^PermitRootLogin no" /etc/ssh/sshd_config
      fix: |
        [source,bash]
        ----
        /usr/bin/sed -i.bak 's/^[\#]*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
        ----
    '12.0':
      references:
        cce:
          - CCE-91013-3
        disa_stig:
          - APPL-12-001100
        srg:
          - SRG-OS-000109-GPOS-00056
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/permitrootlogin/{print $2}'
      fix: "[source,bash]\n----\ninclude_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')\n\nif [[ -z $include_dir ]]; then\n  /usr/bin/sed -i.bk \"1s/.*/Include \\/etc\\/ssh\\/sshd_config.d\\/\\*/\" /etc/ssh/sshd_config\nfi\n\necho \"permitrootlogin no\" >> \"${include_dir}01-mscp-sshd.conf\"\n\nfor file in $(ls ${include_dir}); do\n  if [[ \"$file\" == \"100-macos.conf\" ]]; then\n      continue\n  fi\n  if [[ \"$file\" == \"01-mscp-sshd.conf\" ]]; then\n      break\n  fi\n  /bin/mv ${include_dir}${file} ${include_dir}20-${file}\ndone\n----    \n"
    '13.0':
      references:
        cce:
          - CCE-91893-8
        disa_stig:
          - N/A
        srg:
          - N/A
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/permitrootlogin/{print $2}'
      fix: "[source,bash]\n----\ninclude_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')\n\nif [[ -z $include_dir ]]; then\n  /usr/bin/sed -i.bk \"1s/.*/Include \\/etc\\/ssh\\/sshd_config.d\\/\\*/\" /etc/ssh/sshd_config\nfi\n\necho \"permitrootlogin no\" >> \"${include_dir}01-mscp-sshd.conf\"\n\nfor file in $(ls ${include_dir}); do\n  if [[ \"$file\" == \"100-macos.conf\" ]]; then\n      continue\n  fi\n  if [[ \"$file\" == \"01-mscp-sshd.conf\" ]]; then\n      break\n  fi\n  /bin/mv ${include_dir}${file} ${include_dir}20-${file}\ndone\n----    \n"
