id: os_system_wide_applications_configure
title: Ensure Appropriate Permissions Are Enabled for System Wide Applications
discussion: |
  Applications in the System Applications Directory (/Applications) _MUST_ not be world-writable.
check: |
  /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 -ls | /usr/bin/wc -l | /usr/bin/xargs
result:
  integer: 0
fix: |
  [source,bash]
  ----
  IFS=$'\n'
  for apps in $( /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 ); do
    /bin/chmod -R o-w "$apps"
  done
  ----
references:
  disa:
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    cci:
      - None
  nist:
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85514-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.5 (level 1)
          controls v8:
            - 3.3
    '12.0':
      references:
        cce:
          - CCE-91117-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.5 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91899-5
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.5 (level 1)
          controls v8:
            - 3.3
