id: os_sshd_login_grace_time_configure
title: Set Login Grace Time to $ODV
discussion: |
  If SSHD is enabled then it _MUST_ be configured to wait only $ODV seconds before timing out logon attempts.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: $OS_VALUE
result:
  integer: 1
fix: $OS_VALUE
references:
  disa:
    cci:
      - CCI-001133
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - SC-10
    800-53r4:
      - SC-10
    800-171r2:
      - 3.13.9
  cce:
    - $OS_VALUE
odv:
  hint: Number of seconds.
  recommended: 30
  stig: 30
tags:
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85384-6
        disa_stig:
          - APPL-11-000053
        srg:
          - SRG-OS-000163-GPOS-00072
      check: |
        /usr/bin/grep -c "^LoginGraceTime $ODV" /etc/ssh/sshd_config
      fix: |
        [source,bash]
        ----
        /usr/bin/sed -i.bak 's/.*LoginGraceTime.*/LoginGraceTime $ODV/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
        ----
    '12.0':
      references:
        cce:
          - CCE-91012-5
        disa_stig:
          - APPL-12-000053
        srg:
          - SRG-OS-000163-GPOS-00072
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/logingracetime/{print $2}'
      fix: "[source,bash]\n----\ninclude_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')\n\nif [[ -z $include_dir ]]; then\n  /usr/bin/sed -i.bk \"1s/.*/Include \\/etc\\/ssh\\/sshd_config.d\\/\\*/\" /etc/ssh/sshd_config\nfi\n\necho \"logingracetime $ODV\" >> \"${include_dir}01-mscp-sshd.conf\"\n\nfor file in $(ls ${include_dir}); do\n  if [[ \"$file\" == \"100-macos.conf\" ]]; then\n      continue\n  fi\n  if [[ \"$file\" == \"01-mscp-sshd.conf\" ]]; then\n      break\n  fi\n  /bin/mv ${include_dir}${file} ${include_dir}20-${file}\ndone\n----  \n"
    '13.0':
      references:
        cce:
          - CCE-91892-0
        disa_stig:
          - N/A
        srg:
          - N/A
      check: |
        /usr/sbin/sshd -T | /usr/bin/awk '/logingracetime/{print $2}'
      fix: "[source,bash]\n----\ninclude_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')\n\nif [[ -z $include_dir ]]; then\n  /usr/bin/sed -i.bk \"1s/.*/Include \\/etc\\/ssh\\/sshd_config.d\\/\\*/\" /etc/ssh/sshd_config\nfi\n\necho \"logingracetime $ODV\" >> \"${include_dir}01-mscp-sshd.conf\"\n\nfor file in $(ls ${include_dir}); do\n  if [[ \"$file\" == \"100-macos.conf\" ]]; then\n      continue\n  fi\n  if [[ \"$file\" == \"01-mscp-sshd.conf\" ]]; then\n      break\n  fi\n  /bin/mv ${include_dir}${file} ${include_dir}20-${file}\ndone\n----  \n"
