id: os_system_wide_applications_configure
title: Ensure Appropriate Permissions Are Enabled for System Wide Applications
discussion: |
  Applications in the System Applications Directory (/Applications) _MUST_ not be world-writable.
references:
  nist:
    cce:
      macos_26:
        - CCE-95320-8
      macos_15:
        - CCE-94314-2
      macos_14:
        - CCE-92911-7
  cis:
    benchmark:
      macos_26:
        - 5.1.5 (level 1)
      macos_15:
        - 5.1.5 (level 1)
      macos_14:
        - 5.1.5 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    enforcement_info:
      check:
        shell: /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 -ls | /usr/bin/wc -l | /usr/bin/xargs
        result:
          integer: 0
      fix:
        shell: |-
          IFS=$'\n'
          for apps in $( /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 ); do
            /bin/chmod -R o-w "$apps"
          done
tags:
  - cisv8
