id: os_sudo_timeout_configure
title: Configure Sudo Timeout Period to $ODV
discussion: |
  The file /etc/sudoers _MUST_ include a timestamp_timout of $ODV.
check: |
  /usr/bin/find /etc/sudoers* -type f -exec /usr/bin/grep -E "^Defaults\s+timestamp_timeout=$ODV" '{}' \; | /usr/bin/wc -l | /usr/bin/xargs
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/find /etc/sudoers* -type f -exec sed -i '' '/timestamp_timeout/d' '{}' \;
  /bin/echo "Defaults timestamp_timeout=$ODV" >> /etc/sudoers.d/mscp
  ----
references:
  cce: |-
    $OS_VALUE
  cci:
  - N/A
  800-53r5:
  - N/A
  800-53r4:
  - N/A
  srg:
  - N/A
  disa_stig: |-
    $OS_VALUE
  cis:
    benchmark:
    - 5.3 (level 1)
    controls v8:
    - 4.3
odv:
  hint: Number of minutes.
  recommended: 0
  cis_lvl1: 0
  cis_lvl2: 0
tags:
- 800-53r5_low
- 800-53r5_moderate
- 800-53r5_high
- cnssi-1253
- cis_lvl1
- cis_lvl2
- cisv8
mobileconfig: false
mobileconfig_info:
OS_specifics:
  macOS:
    '12':
      references:
        cce:
        - CCE-91116-4
        disa_stig:
        - N/A
    '11':
      references:
        cce:
        - CCE-85512-2
        disa_stig:
        - N/A
