id: os_sudoers_tty_configure
title: Configure Sudoers to Authenticate Users on a Per -tty Basis
discussion: |
  The file /etc/sudoers _MUST_ be configured to include tty_tickets.

  This rule ensures that the "sudo" command will prompt for the administrator's password at least once in each newly opened terminal window. This prevents a malicious user from taking advantage of an unlocked computer or an abandoned logon session by bypassing the normal password prompt requirement. Without the "tty_tickets" option, all open local and remote logon sessions would be authenticated to use sudo without a password for the duration of the configured password timeout window.
check: |
  /usr/bin/grep -Ec "^Defaults tty_tickets" /etc/sudoers
result: 1
fix: |
  [source,bash]
  ----
  /bin/cp /etc/sudoers /etc/sudoers.bk; /bin/echo "Defaults tty_tickets" >> /etc/sudoers
  ----
references:
  disa:
    cci:
      - CCI-000366
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - CM-5(1)
      - IA-11
    800-53r4:
      - IA-11
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cnssi-1253
  - stig
severity: high
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '10.15':
      references:
        cce:
          - CCE-84799-6
        disa_stig:
          - AOSX-15-004021
        srg:
          - SRG-OS-000480-GPOS-00227
        sfr:
          - N/A
