id: os_sshd_client_alive_count_max_configure
title: Set SSHD Active Client Alive Maximum to $ODV
discussion: |
  If SSHD is enabled it _MUST_ be configured with an Active Client Alive Maximum Count set to $ODV. Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session or an incomplete login attempt will also free up resources committed by the managed network element.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/grep -c "^ClientAliveCountMax $ODV" /etc/ssh/sshd_config
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/.*ClientAliveCountMax.*/ClientAliveCountMax $ODV/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
  ----
references:
  cce: |-
    $OS_VALUE
  cci:
  - CCI-001133
  800-53r5:
  - SC-10
  800-53r4:
  - SC-10
  srg:
  - SRG-OS-000163-GPOS-00072
  disa_stig: |-
    $OS_VALUE
  800-171r2:
  - 3.13.9
odv:
  hint: Number of seconds.
  recommended: 0
  stig: 0
tags:
- 800-53r5_moderate
- 800-53r5_high
- 800-53r4_moderate
- 800-53r4_high
- 800-171
- cnssi-1253
- stig
severity: medium
mobileconfig: false
mobileconfig_info:
OS_specifics:
  macOS:
    '12':
      references:
        cce:
        - CCE-91007-5
        disa_stig:
        - APPL-12-000052
    '11':
      references:
        cce:
        - CCE-85456-2
        disa_stig:
        - APPL-11-000052
    '10.15':
      references:
        cce:
        - CCE-84792-1
        disa_stig:
        - AOSX-15-000052
