id: os_sudo_timeout_configure
title: Configure Sudo Timeout Period to $ODV
discussion: |
  The file /etc/sudoers _MUST_ include a timestamp_timout of $ODV.
check: |
  /usr/bin/sudo /usr/bin/sudo -V | /usr/bin/grep -c "Authentication timestamp timeout: $ODV.0 minutes"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/find /etc/sudoers* -type f -exec sed -i '' '/timestamp_timeout/d' '{}' \;
  /bin/echo "Defaults timestamp_timeout=$ODV" >> /etc/sudoers.d/mscp
  ----
references:
  cce:
    - $OS_VALUE
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
  cci:
    - None
odv:
  hint: Number of minutes.
  recommended: 0
  cis_lvl1: 0
  cis_lvl2: 0
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85512-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.3 (level 1)
          controls v8:
            - 4.3
    '12.0':
      references:
        cce:
          - CCE-91116-4
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.3 (level 1)
          controls v8:
            - 4.3
    '13.0':
      references:
        cce:
          - CCE-91895-3
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.4 (level 1)
          controls v8:
            - 4.3
