id: os_ssh_server_alive_interval_configure
title: Configure SSH ServerAliveInterval option set to $ODV
discussion: "SSH _MUST_ be configured with an Active Server Alive Maximum Count set\
  \ to $ODV. \n\nSetting the Active Server Alive Maximum Count to $ODV (seconds) will\
  \ log users out after an organization defined value interval of inactivity.\n\n\
  NOTE: /etc/ssh/ssh_config will be automatically modified to its original state following\
  \ any update or major upgrade to the operating system.\n"
check: |
  /usr/bin/awk '/^ServerAliveInterval/{print $2}' /etc/ssh/ssh_config
result:
  integer: $ODV
fix: |
  [source,bash]
  ----
  /usr/bin/grep -q '^ServerAliveInterval' /etc/ssh/ssh_config && /usr/bin/sed -i.bak  's/.*ServerAliveInterval.*/ServerAliveInterval $ODV/' /etc/ssh/ssh_config || /bin/echo 'ServerAliveInterval $ODV' >> /etc/ssh/ssh_config
  ----
references:
  cce: |-
    $OS_VALUE
  cci:
  - N/A
  800-53r5:
  - SC-10
  - AC-12
  800-53r4:
  - SC-10
  srg:
  - N/A
  disa_stig: |-
    $OS_VALUE
  800-171r2:
  - 3.13.9
odv:
  hint: Number of seconds.
  default: 900
tags:
- 800-53r5_moderate
- 800-53r5_high
- 800-53r4_moderate
- 800-53r4_high
- 800-171
- cnssi-1253
mobileconfig: false
mobileconfig_info:
OS_specifics:
  macOS:
    '12':
      references:
        cce:
        - CCE-91006-7
        disa_stig:
        - N/A
    '11':
      references:
        cce:
        - CCE-85381-2
        disa_stig:
        - N/A
    '10.15':
      references:
        cce:
        - CCE-84919-0
        disa_stig:
        - N/A
