id: os_sshd_key_exchange_algorithm_configure
title: "Configure SSHD to Use Secure Key Exchange Algorithms"
discussion: |
  If SSHD is enabled then it _MUST_ be configured to limit the Message Key Exchange Algorithms. This is required for compliance with the DISA STIG for macOS.

  In order to meet FIPS 140-3 compliance, please use the configuration in *os_sshd_fips_compliant* which follows the recommended guidelines from Apple in the manpage *apple_ssh_and_fips* and found on

  link:https://support.apple.com/guide/certifications/macos-security-certifications-apc35eb3dc4fa/web[]

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/sbin/sshd -T | /usr/bin/grep -ci "^KexAlgorithms diffie-hellman-group-exchange-sha256"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

  if [[ -z $include_dir ]]; then
    /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
  fi

  /usr/bin/grep -qxF 'KexAlgorithms diffie-hellman-group-exchange-sha256' "${include_dir}01-mscp-sshd.conf" 2>/dev/null || echo "KexAlgorithms diffie-hellman-group-exchange-sha256" >> "${include_dir}01-mscp-sshd.conf"

  for file in $(ls ${include_dir}); do
    if [[ "$file" == "100-macos.conf" ]]; then
        continue
    fi
    if [[ "$file" == "01-mscp-sshd.conf" ]]; then
        break
    fi
    /bin/mv ${include_dir}${file} ${include_dir}20-${file}
  done
  ----
references:
  cce:
    - CCE-91891-2
  cci:
    - N/A
  800-53r5:
    - AC-17(2)
    - IA-7
    - MA-4(6)
  800-53r4:
    - IA-7
    - AC-17(2)
    - MA-4(6)
  srg:
    - N/A
  disa_stig:
    - APPL-13-000056
  800-171r2:
    - N/A
  cmmc:
    - AC.L2-3.1.13
macOS:
  - "13.0"
tags:
  - cnssi-1253_moderate
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - stig
severity: "high"
mobileconfig: false
mobileconfig_info: