id: os_time_offset_limit_configure
title: Ensure Time Offset Within Limits
discussion: |
  The macOS system time  _MUST_ be monitored to not drift more than four minutes and thirty seconds.
check: |
  /usr/bin/sntp $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}') | /usr/bin/awk -F'.' '/\+\/\-/{if (substr($1,2) >= 270) {print "No"} else {print "Yes"}}'
result: 'Yes'
fix: |
  [source,bash]
  ----
  /usr/bin/sntp -Ss $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}')
  ----
references:
  disa:
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    cci:
      - None
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-85516-3
        cis:
          benchmark:
            - 2.2.2 (level 1)
          controls v8:
            - 8.4
    '12.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91119-8
        cis:
          benchmark:
            - 2.2.2 (level 1)
          controls v8:
            - 8.4
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91903-5
        cis:
          benchmark:
            - 2.3.2.2 (level 1)
          controls v8:
            - 8.4
