id: os_world_writable_system_folder_configure
title: Ensure No World Writable Files Exist in the System Folder
discussion: |
  Folders in /System/Volumes/Data/System _MUST_ not be world-writable.
check: |
  /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -v "Drop Box" | /usr/bin/wc -l | /usr/bin/xargs
result:
  integer: 0
fix: |
  [source,bash]
  ----
  IFS=$'\n'
  for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -v "Drop Box" ); do
    /bin/chmod -R o-w "$sysPermissions"
  done
  ----
references:
  disa:
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    cci:
      - None
  nist:
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85518-9
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.6 (level 1)
          controls v8:
            - 3.3
    '12.0':
      references:
        cce:
          - CCE-91121-4
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.6 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91912-6
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 5.1.6 (level 1)
          controls v8:
            - 3.3
