id: os_world_writable_library_folder_configure
title: Ensure No World Writable Files Exist in the Library Folder
discussion: |
  Folders in /System/Volumes/Data/Library _MUST_ not be world-writable.

  NOTE: Some vendors are known to create world-writable folders to the System Library folder. You may need to add more exclusions to this check and fix to match your environment.
references:
  nist:
    cce:
      macos_26:
        - CCE-95332-3
      macos_15:
        - CCE-94326-6
      macos_14:
        - CCE-92923-2
  cis:
    benchmark:
      macos_26:
        - 5.1.7 (level 2)
      macos_15:
        - 5.1.7 (level 2)
      macos_14:
        - 5.1.7 (level 2)
    controls_v8:
      - 3.3
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl2
    '15.0':
      benchmarks:
        - name: cis_lvl2
    '14.0':
      benchmarks:
        - name: cis_lvl2
      enforcement_info:
        check:
          shell: /usr/bin/find /System/Volumes/Data/Library -type d -perm -2 -ls 2>&1 | /usr/bin/grep -v Caches | /usr/bin/grep -v /Preferences/Audio/Data | /usr/bin/wc -l | /usr/bin/xargs
          result:
            integer: 0
        fix:
          shell: |-
            IFS=$'\n'
            for libPermissions in $( /usr/bin/find /System/Volumes/Data/Library -type d -perm -2 2>&1 | /usr/bin/grep -v Caches | /usr/bin/grep -v /Preferences/Audio/Data ); do
              /bin/chmod -R o-w "$libPermissions"
            done
    enforcement_info:
      check:
        shell: /usr/bin/find /Library -type d -perm -002 ! -perm -1000 ! -xattrname com.apple.rootless 2>/dev/null | /usr/bin/wc -l | /usr/bin/xargs
        result:
          integer: 0
      fix:
        shell: |-
          IFS=$'\n'
          for libPermissions in $(/usr/bin/find /Library -type d -perm -002 ! -perm -1000 ! -xattrname com.apple.rootless 2>/dev/null); do
            /bin/chmod -R o-w "$libPermissions"
          done
tags:
  - cisv8
