id: icloud_appleid_system_settings_disable
title: Disable the System Setting for Apple ID
discussion: "The system setting for Apple ID _MUST_ be disabled.\n\nDisabling the system setting prevents login to Apple ID and iCloud. \n"
check: |
  /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledSystemSettings"]/following-sibling::*[1]' - | /usr/bin/grep -c com.apple.systempreferences.AppleIDSettings
result: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-20
      - AC-20(1)
      - CM-7
      - CM-7(1)
    800-53r4:
      - CM-7
      - CM-7(1)
      - AC-20
      - AC-20(1)
    800-171r2:
      - 3.1.20
      - 3.4.6
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cisv8
severity: high
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledSystemSettings:
      - com.apple.systempreferences.AppleIDSettings
os_specifics:
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91939-9
        cis:
          benchmark:
            - N/A
          controls v8:
            - 4.1
            - 4.8
