id: system_settings_personalized_advertising_disable
title: Disable Personalized Advertising
discussion: "Ad tracking and targeted ads _MUST_ be disabled.\n\nThe information system _MUST_ be configured to provide only essential capabilities. Disabling ad tracking ensures that applications and advertisers are unable to track users' interests and deliver targeted advertisements.  \n"
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - cis_lvl1_byod
  - cis_lvl2_byod
  - cis_lvl2_enterprise
  - cis_lvl1_enterprise
  - ios
severity: ''
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowApplePersonalizedAdvertising: false
os_specifics:
  iOS:
    '16.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - N/A
        cis:
          benchmark:
            - 2.2.1.5 (level 1 - End-User Owned Devices)
            - 3.2.1.11 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 4.8
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91968-8
        cis:
          benchmark:
            - 2.6.3 (level 1)
          controls v8:
            - 4.8
