id: system_settings_loginwindow_prompt_username_password_enforce
title: Configure Login Window to Prompt for Username and Password
discussion: "The login window _MUST_ be configured to prompt all users for both a username and a password. \n\nBy default, the system displays a list of known users on the login window, which can make it easier for a malicious user to gain access to someone else's account. Requiring users to type in both their username and password mitigates the risk of unauthorized users gaining access to the information system. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
  .objectForKey('SHOWFULLNAME').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - IA-2
  800-53r4:
    - IA-2
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - 3.5.1
    - 3.5.2
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: low
mobileconfig: true
mobileconfig_info:
  com.apple.loginwindow:
    SHOWFULLNAME: true
os_specifics:
  '13.0':
    references:
      cce:
        - CCE-91965-4
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 2.10.4 (level 1)
        controls v8:
          - 4.1
