id: system_settings_time_machine_auto_backup_enable
title: Configure Time Machine for Automatic Backups
discussion: |
  Automatic backups _MUST_ be enabled when using Time Machine.
references:
  nist:
    cce:
      macos_26:
        - CCE-95409-9
      macos_15:
        - CCE-94402-5
      macos_14:
        - CCE-92997-6
  cis:
    benchmark:
      macos_26:
        - 2.3.4.1 (level 2)
      macos_15:
        - 2.3.4.1 (level 2)
      macos_14:
        - 2.3.4.1 (level 2)
    controls_v8:
      - 11.2
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl2
    '15.0':
      benchmarks:
        - name: cis_lvl2
    '14.0':
      benchmarks:
        - name: cis_lvl2
    enforcement_info:
      check:
        shell: |-
          /usr/bin/osascript -l JavaScript << EOS
          $.NSUserDefaults.alloc.initWithSuiteName('com.apple.TimeMachine')\
          .objectForKey('AutoBackup').js
          EOS
        result:
          string: 'true'
    introduced: '-1'
tags:
  - cisv8
mobileconfig_info:
  - PayloadType: com.apple.TimeMachine
    PayloadContent:
      - AutoBackup: true
