id: system_settings_bluetooth_menu_enable
title: Enable Bluetooth Menu
discussion: |
  The bluetooth menu _MUST_ be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
  .objectForKey('Bluetooth').js
  EOS
result: 18
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.controlcenter:
    Bluetooth: 18
os_specifics:
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91937-3
        cis:
          benchmark:
            - 2.4.2 (level 1)
          controls v8:
            - 4.8
            - 13.9
