id: system_settings_guest_account_disable
title: Disable the Guest Account
discussion: "Guest access _MUST_ be disabled. \n\nTurning off guest access prevents anonymous users from accessing files.\n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  function run() {
    let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
  .objectForKey('DisableGuestAccount'))
    let pref2 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
  .objectForKey('EnableGuestAccount'))
    if ( pref1 == true && pref2 == false ) {
      return("true")
    } else {
      return("false")
    }
  }
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-2
      - AC-2(9)
    800-53r4:
      - AC-2
      - AC-2(9)
    800-171r2:
      - 3.5.1
      - 3.5.2
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: high
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    DisableGuestAccount: true
    EnableGuestAccount: false
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91953-0
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.12.1 (level 1)
          controls v8:
            - 5.2
            - 6.2
            - 6.8
