id: system_settings_gatekeeper_override_disallow
title: Configure Gatekeeper to Disallow End User Override
discussion: "Gatekeeper _MUST_ be configured with a configuration profile to prevent normal users from overriding its settings. \n\nIf users are allowed to disable Gatekeeper or set it to a less restrictive setting, malware could be introduced into the system. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.systempolicy.managed')\
  .objectForKey('DisableOverride').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - CM-5
      - SI-7(15)
    800-53r4:
      - CM-5
      - SI-7(15)
    800-171r2:
      - 3.4.5
    cce:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.systempolicy.managed:
    DisableOverride: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91951-4
        disa_stig:
          - N/A
        srg:
          - N/A
