id: system_settings_system_wide_preferences_configure
title: Require Administrator Password to Modify System-Wide Preferences
discussion: "The system _MUST_ be configured to require an administrator password in order to modify the system-wide preferences in System Settings. \n\nSome Preference Panes in System Settings contain settings that affect the entire system. Requiring a password to unlock these system-wide settings reduces the risk of a non-authorized user modifying system configurations.\n"
check: |
  authDBs=("system.preferences" "system.preferences.energysaver" "system.preferences.network" "system.preferences.printing" "system.preferences.sharing" "system.preferences.softwareupdate" "system.preferences.startupdisk" "system.preferences.timemachine")
  result="1"
  for section in ${authDBs[@]}; do
    if [[ $(/usr/bin/security -q authorizationdb read "$section" | /usr/bin/xmllint -xpath 'name(//*[contains(text(), "shared")]/following-sibling::*[1])' -) != "false" ]]; then
      result="0"
    fi
  done
  echo $result
result:
  integer: 1
fix: "[source,bash]\n----\nauthDBs=(\"system.preferences\" \"system.preferences.energysaver\" \"system.preferences.network\" \"system.preferences.printing\" \"system.preferences.sharing\" \"system.preferences.softwareupdate\" \"system.preferences.startupdisk\" \"system.preferences.timemachine\")\n\nfor section in ${authDBs[@]}; do\n/usr/bin/security -q authorizationdb read \"$section\" > \"/tmp/$section.plist\"\nkey_value=$(/usr/libexec/PlistBuddy -c \"Print :shared\" \"/tmp/$section.plist\" 2>&1)\n\tif [[ \"$key_value\" == *\"Does Not Exist\"* ]]; then\n  \t\t/usr/libexec/PlistBuddy -c \"Add :shared bool false\" \"/tmp/$section.plist\"\n\telse\n  \t\t/usr/libexec/PlistBuddy -c \"Set :shared false\" \"/tmp/$section.plist\"\n\tfi\n  \t/usr/bin/security -q authorizationdb write \"$section\" < \"/tmp/$section.plist\"\ndone\n----\n"
references:
  cce:
    - $OS_VALUE
  800-53r5:
    - AC-6
    - AC-6(2)
    - AC-6(1)
  800-53r4:
    - AC-6
    - AC-6(1)
    - AC-6(2)
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - 3.1.5
    - 3.1.6
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
  cci:
    - None
  srg:
    - $OS_VALUE
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  '13.0':
    references:
      cce:
        - CCE-91986-0
      disa_stig:
        - N/A
      srg:
        - None
      cis:
        benchmark:
          - 2.6.7 (level 1)
        controls v8:
          - 4.1
