id: system_settings_guest_access_smb_disable
title: Disable Guest Access to Shared SMB Folders
discussion: "Guest access to shared Server Message Block (SMB) folders _MUST_ be disabled. \n\nTurning off guest access prevents anonymous users from accessing files shared via SMB.\n"
check: |
  /usr/bin/defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server AllowGuestAccess
result:
  boolean: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/sysadminctl -smbGuestAccess off
  ----
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    800-171r2:
      - 3.5.1
      - 3.5.2
    800-53r5:
      - AC-2(9)
      - AC-2
    800-53r4:
      - AC-2
      - AC-2(9)
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91952-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.12.2 (level 1)
          controls v8:
            - 3.3
