id: system_settings_location_services_menu_enforce
title: Enable Location Services
discussion: |
  Location Services menu item _MUST_ be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.locationmenu')\
  .objectForKey('ShowSystemServices').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl2
mobileconfig: true
mobileconfig_info:
  com.apple.locationmenu:
    ShowSystemServices: true
os_specifics:
  '13.0':
    references:
      cce:
        - CCE-91963-9
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 2.6.1.2 (level 2)
        controls v8:
          - 4.1
          - 4.8
