id: system_settings_wake_network_access_disable
title: Ensure Wake for Network Access Is Disabled
discussion: |
  Wake for network access _MUST_ be disabled.
check: |
  /usr/bin/pmset -g custom | /usr/bin/awk '/womp/ { sum+=$2 } END {print sum}'
result: 0
fix: |
  [source,bash]
  ----
  /usr/bin/pmset -a womp 0
  ----
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91995-1
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - 2.9.2 (level 1)
          controls v8:
            - 4.8
