id: system_settings_location_services_enable
title: Enable Location Services
discussion: "Location Services _MUST_ be enabled.   \n"
check: |
  /usr/bin/sudo -u _locationd /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.locationd')\
  .objectForKey('LocationServicesEnabled').js
  EOS
result:
  string: 'true'
fix: |
  [source,bash]
  ----
  /usr/bin/defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -bool true; /bin/launchctl kickstart -k system/com.apple.locationd
  ----
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91963-9
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.6.1.1 (level 2)
          controls v8:
            - 4.1
            - 4.8
