id: system_settings_usb_restricted_mode
title: USB Devices Must be Authorized Before Allowing
discussion: |
  USB devices connected to a Mac _MUST_ be authorized.

  [IMPORTANT]
  ====
  This feature is removed if a smartcard is paired or smartcard attribute mapping is configured.
  ====
check: |
  /usr/bin/osascript -l JavaScript << EOS
    function run() {
      let pref1 = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
    .objectForKey('allowUSBRestrictedMode'))
      if ( pref1 == false ) {
        return("false")
      } else {
        return("true")
      }
    }
  EOS
result: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - MP-7
      - SC-41
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUSBRestrictedMode: true
os_specifics:
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - None
          srg:
            - None
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91931-6
        cis:
          benchmark:
            - N/A
          controls v8:
            - N/A
