id: system_settings_install_macos_updates_enforce
title: Enforce macOS Updates are Automatically Installed
discussion: |
  Software Update _MUST_ be configured to enforce automatic installation of macOS updates is enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
  .objectForKey('AutomaticallyInstallMacOSUpdates').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.SoftwareUpdate:
    AutomaticallyInstallMacOSUpdates: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91957-1
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 1.4 (level 1)
          controls v8:
            - 7.3
            - 7.4
