id: system_settings_rae_disable
title: Disable Remote Apple Events
discussion: "If the system does not require Remote Apple Events, support for Apple Remote Events is non-essential and _MUST_ be disabled.\n\nThe information system _MUST_ be configured to provide only essential capabilities. Disabling Remote Apple Events helps prevent the unauthorized connection of devices, the unauthorized transfer of information, and unauthorized tunneling. \n"
check: |
  /bin/launchctl print-disabled system | /usr/bin/grep -c '"com.apple.AEServer" => disabled'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/sbin/systemsetup -setremoteappleevents off
  /bin/launchctl disable system/com.apple.AEServer
  ----
  NOTE: Systemsetup with -setremoteappleevents flag will fail unless you grant Full Disk Access to systemsetup or it's parent process. Requires supervision.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - AC-3
    - AC-17
  800-53r4:
    - AC-3
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - 3.1.1
    - 3.1.2
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  '13.0':
    references:
      cce:
        - CCE-91970-4
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 2.3.3.7 (level 1)
        controls v8:
          - 4.1
          - 4.8
