id: system_settings_diagnostics_reports_disable
title: Disable Sending Diagnostic and Usage Data to Apple
discussion: "The ability to submit diagnostic data to Apple _MUST_ be disabled.\n\nThe information system _MUST_ be configured to provide only essential capabilities. Disabling the submission of diagnostic and usage information will mitigate the risk of unwanted data being sent to Apple. \n"
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - CCI-001199
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-20
      - SC-7(10)
      - SI-11
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cis_lvl2
  - cisv8
  - cis_lvl1_byod
  - cis_lvl2_byod
  - stig
  - ios
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
severity: medium
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowDiagnosticSubmission: false
os_specifics:
  iOS:
    '16.0':
      references:
        cce:
          - N/A
        disa_stig:
          - AIOS-16-013400
        srg:
          - None
        sfr:
          - 'FMT_SMF_EXT.1.1 #47a'
        cis:
          benchmark:
            - 2.2.1.12 (level 1 - End-User Owned Devices)
            - 3.2.1.25 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 4.8
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91945-6
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - 2.6.2 (level 2)
          controls v8:
            - 4.1
            - 4.8
