id: system_settings_filevault_enforce
title: Enforce FileVault
discussion: |
  FileVault _MUST_ be enforced.

  The information system implements cryptographic mechanisms to protect the confidentiality and integrity of information stored on digital media during transport outside of controlled areas.
check: |
  dontAllowDisable=$(/usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
  .objectForKey('dontAllowFDEDisable').js
  EOS
  )
  fileVault=$(/usr/bin/fdesetup status | /usr/bin/grep -c "FileVault is On.")
  if [[ "$dontAllowDisable" == "true" ]] && [[ "$fileVault" == 1 ]]; then
    echo "1"
  else
    echo "0"
  fi
result: 1
fix: |
  NOTE: See the FileVault supplemental to implement this rule.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - SC-28
      - SC-28(1)
    800-53r4:
      - SC-28
      - SC-28(1)
    800-171r2:
      - 3.13.16
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    dontAllowFDEDisable: true
os_specifics:
  macOS:
    '13.0':
      references:
        disa:
          disa_stig:
            - N/A
          srg:
            - N/A
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91946-4
        cis:
          benchmark:
            - 2.6.5 (level 1)
          controls v8:
            - 3.6
            - 3.11
