id: system_settings_wifi_disable_when_connected_to_ethernet
title: Disable Wi-Fi When Connected to Ethernet
discussion: "The macOS should be configured to automatically disable Wi-Fi when connected to ethernet. \n\nThe use of Wi-Fi to connect to unauthorized networks may facilitate the exfiltration of mission data. Therefore, wireless networking capabilities internally embedded within information system components should be disabled when not intended to be used. \n\nNOTE: If the system requires Wi-Fi to connect to an authorized network, this is not applicable.\n"
check: |
  The technology does not support this requirement. This is an applicable-does not meet finding.
fix: |
  This requirement is a permanent finding and cannot be fixed. An appropriate mitigation for the system must be implemented, but this finding cannot be considered fixed.
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-4
      - AC-18(1)
      - AC-18(3)
    800-53r4:
      - AC-4
      - AC-18(1)
      - AC-18(3)
    800-171r2:
      - 3.1.3
      - 3.1.17
    cce:
      - $OS_VALUE
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - permanent
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91999-3
        disa_stig:
          - N/A
        srg:
          - N/A
