id: system_settings_time_machine_auto_backup_enable
title: Configure Time Machine for Automatic Backups
discussion: "Automatic backups _MUST_ be enabled when using Time Machine. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.TimeMachine')\
  .objectForKey('AutoBackup').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.TimeMachine:
    AutoBackup: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91987-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.3.4.1 (level 2)
          controls v8:
            - 11.2
