id: system_settings_handoff_disable
title: Disable Handoff
discussion: "Handoff _MUST_ be disabled. \n\nHandoff allows you to continue working on a document or project when the user switches from one Apple device to another. Disabling Handoff prevents data transfers to unauthorized devices.\n"
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  disa_stig:
    - $OS_VALUE
  srg:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - cis_lvl2_byod
  - cis_lvl2_enterprise
  - cisv8
severity: ''
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowActivityContinuation: false
os_specifics:
  ios:
    '16.0':
      references:
        cce:
          - N/A
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.2.1.11 (level 2 - End-User Owned Devices)
            - 3.2.1.24 (level 2 - Institutionally-Owned Devices)
          controls v8:
            - 3.3
