id: system_settings_screensaver_ask_for_password_delay_enforce
title: Enforce Session Lock After Screen Saver is Started
discussion: "A screen saver _MUST_ be enabled and the system _MUST_ be configured to require a password to unlock once the screensaver has been on for a maximum of $ODV seconds. \n\nAn unattended system with an excessive grace period is vulnerable to a malicious user. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  function run() {
    let delay = ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.screensaver')\
  .objectForKey('askForPasswordDelay'))
    if ( delay <= $ODV ) {
      return("true")
    } else {
      return("false")
    }
  }
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-11
    800-53r4:
      - AC-11
    800-171r2:
      - 3.1.10
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
odv:
  hint: Number of seconds.
  recommended: 5
  cis_lvl1: 5
  cis_lvl2: 5
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.screensaver:
    askForPasswordDelay: $ODV
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91973-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.10.2 (level 1)
          controls v8:
            - 4.7
