id: system_settings_touchid_unlock_disable
title: Disable TouchID for Unlocking the Device
discussion: "TouchID enables the ability to unlock a Mac system with a user's fingerprint. \n\nTouchID _MUST_ be disabled for \"Unlocking your Mac\" on all macOS devices that are capable of using Touch ID. \n\nThe system _MUST_ remain locked until the user establishes access using an authorized identification and authentication method. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowFingerprintForUnlock').js
  EOS
result:
  string: 'false'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-11
    800-53r4:
      - AC-11
    800-171r2:
      - 3.1.10
  cce:
    - $OS_VALUE
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowFingerprintForUnlock: false
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91994-4
        disa_stig:
          - N/A
        srg:
          - N/A
