id: system_settings_time_machine_encrypted_configure
title: Ensure Time Machine Volumes are Encrypted
discussion: |
  Time Machine volumes _MUST_ be encrypted.
check: |
  /usr/bin/sudo /usr/bin/defaults read /Library/Preferences/com.apple.TimeMachine.plist | grep -c NotEncrypted
result:
  integer: 0
fix: |
  . Go to System Settings -> Time Machine
  . Click *Select Disk*
  . Select existing Backup Disk under *Available Disks*
  . Click *Encrypt Backups*
  . Click *Use Disk*
references:
  cce:
    - CCE-92998-4
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r3:
    - N/A
  cis:
    benchmark:
      - 2.3.4.2 (level 1)
    controls v8:
      - 3.6
      - 3.11
      - 11.3
macOS:
  - '14.0'
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info:
