id: system_settings_diagnostics_reports_disable
title: Disable Sending Diagnostic and Usage Data to Apple
discussion: "The ability to submit diagnostic data to Apple _MUST_ be disabled.\n\nThe information system _MUST_ be configured to provide only essential capabilities. Disabling the submission of diagnostic and usage information will mitigate the risk of unwanted data being sent to Apple. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  function run() {
  let pref1 = $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SubmitDiagInfo')\
  .objectForKey('AutoSubmit').js
  let pref2 = $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
  .objectForKey('allowDiagnosticSubmission').js
  if ( pref1 == false && pref2 == false ){
      return("true")
  } else {
      return("false")
  }
  }
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - SI-11
      - AC-20
      - SC-7(10)
    800-53r4:
      - AC-20
      - SI-11
    800-171r2:
      - 3.1.20
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.SubmitDiagInfo:
    AutoSubmit: false
  com.apple.applicationaccess:
    allowDiagnosticSubmission: false
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91945-6
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.6.2 (level 2)
          controls v8:
            - 4.1
            - 4.8
