id: system_settings_cd_dvd_sharing_disable
title: Disable CD/DVD Sharing
discussion: "CD/DVD Sharing _MUST_ be disabled. \n"
check: |
  /usr/bin/pgrep -q ODSAgent; /bin/echo $?
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ODSAgent.plist
  ----
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - CM-7
    - CM-7(1)
  800-53r4:
    - CM-7
    - CM-7(1)
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91942-3
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.3.3.1 (level 1)
          controls v8:
            - 4.1
            - 4.8
