id: system_settings_gatekeeper_identified_developers_allowed
title: Apply Gatekeeper Settings to Block Applications from Unidentified Developers
discussion: |
  The information system implements cryptographic mechanisms to authenticate software prior to installation.

  Gatekeeper settings must be configured correctly to only allow the system to run applications downloaded from the Mac App Store or applications signed with a valid Apple Developer ID code. Administrator users will still have the option to override these settings on a per-app basis. Gatekeeper is a security feature that ensures that applications must be digitally signed by an Apple-issued certificate in order to run. Digital signatures allow the macOS to verify that the application has not been modified by a malicious third party.
check: |
  /usr/sbin/spctl --status --verbose | /usr/bin/grep -c "developer id enabled"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/sbin/spctl --global-enable; /usr/sbin/spctl --enable
  ----
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - CM-14
      - CM-5
      - SI-7(15)
      - SI-7(1)
    800-53r4:
      - CM-5(3)
      - CM-5
      - SI-7(15)
    800-171r2:
      - 3.4.5
    cce:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.systempolicy.control:
    AllowIdentifiedDevelopers: true
    EnableAssessment: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91950-6
        disa_stig:
          - N/A
        srg:
          - N/A
