id: system_settings_siri_prefpane_disable
title: Disable the System Preference Pane for Siri
discussion: "This is required for compliance with the DISA STIG for macOS. \n\nThe domain *com.apple.systempreferences* has been deprecated by Apple in macOS 13. The recommended way to disable System Setting Panes is to use the *DisabledSystemSettings* key.\n\nlink:https://developer.apple.com/documentation/devicemanagement/systempreferences[]\n"
check: |
  /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledPreferencePanes"]/following-sibling::*[1]' - | /usr/bin/grep -c com.apple.preference.speech
result: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - CCI-000381
      - CCI-001774
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - stig
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledPreferencePanes:
      - com.apple.preference.speech
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - N/A
        disa_stig:
          - APPL-13-002053
        srg:
          - SRG-OS-000095-GPOS-00049
          - SRG-OS-000370-GPOS-00155
        sfr:
          - N/A
        cis:
          benchmark:
            - N/A
          controls v8:
            - N/A
