id: system_settings_time_server_enforce
title: Enforce macOS Time Synchronization
discussion: |
  Time synchronization _MUST_ be enforced on all networked systems.

  This rule ensures the uniformity of time stamps for information systems with multiple system clocks and systems connected over a network.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.timed')\
  .objectForKey('TMAutomaticTimeOnlyEnabled').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - AU-12(1)
    - SC-45(1)
  800-53r4:
    - AU-8(1)
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - 3.3.7
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-171
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.ManagedClient.preferences:
    com.apple.timed:
      TMAutomaticTimeOnlyEnabled: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91990-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.3.2.1 (level 1)
          controls v8:
            - 8.4
