id: system_settings_wifi_disable
title: Disable Wi-Fi Interface
discussion: "The macOS system must be configured with Wi-Fi support software disabled if not connected to an authorized trusted network. \n\nAllowing devices and users to connect to or from the system without first authenticating them allows untrusted access and can lead to a compromise or attack. Since wireless communications can be intercepted  it is necessary to use encryption to protect the confidentiality of information in transit.Wireless technologies include  for example  microwave  packet radio (UHF/VHF)  802.11x  and Bluetooth. Wireless networks use authentication protocols (e.g.  EAP/TLS  PEAP)  which provide credential protection and mutual authentication.\n\nNOTE: If the system requires Wi-Fi to connect to an authorized network, this is not applicable.\n"
check: |
  /usr/sbin/networksetup -listallnetworkservices | /usr/bin/grep -c "*Wi-Fi"
result: 1
fix: |
  To disable Wi-Fi on a macOS system, run the following command.
  [source,bash]
  ----
  /usr/sbin/networksetup -setnetworkserviceenabled "Wi-Fi" off
  ----
references:
  disa:
    cci:
      - N/A
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-4
      - AC-18
      - AC-18(1)
      - AC-18(3)
    800-53r4:
      - AC-4
      - AC-18(1)
      - AC-18(3)
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - manual
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91998-5
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - N/A
          controls v8:
            - 4.2
            - 12.6
