id: system_settings_force_date_and_time_enable
title: Ensure Force automatic date and time is set to Enabled
discussion: |
  Automatic date and time _MUST_ be enabled.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    sfr:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AU-12(1)
      - SC-45(1)
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1_byod
  - cis_lvl2_byod
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
  - 800-53r5
severity: ''
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    forceAutomaticDateAndTime: true
os_specifics:
  iOS:
    '16.0':
      references:
        cce:
          - N/A
        disa_stig:
          - N/A
        srg:
          - None
        sfr:
          - N/A
        cis:
          benchmark:
            - 2.2.1.7 (level 1 - End-User Owned Devices)
            - 3.2.1.17 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 8.4
