id: system_settings_personalized_advertising_disable
title: Disable Personalized Advertising
discussion: "Ad tracking and targeted ads _MUST_ be disabled.\n\nThe information system _MUST_ be configured to provide only essential capabilities. Disabling ad tracking ensures that applications and advertisers are unable to track users' interests and deliver targeted advertisements.  \n"
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - cis_lvl1_byod
  - cis_lvl2_byod
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
severity: ''
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowApplePersonalizedAdvertising: false
os_specifics:
  ios:
    '16.0':
      references:
        cce:
          - N/A
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.2.1.5 (level 1 - End-User Owned Devices)
            - 3.2.1.11 (level 1 - Institutionally-Owned Devices)
          controls v8:
            - 4.8
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91968-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.6.3 (level 1)
          controls v8:
            - 4.8
