id: system_settings_screensaver_password_enforce
title: Enforce Screen Saver Password
discussion: "Users _MUST_ authenticate when unlocking the screen saver. \n\nThe screen saver acts as a session lock and prevents unauthorized users from accessing the current user's account.\n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.screensaver')\
  .objectForKey('askForPassword').js
  EOS
result: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-11
    800-53r4:
      - AC-11
    800-171r2:
      - 3.1.10
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.screensaver:
    askForPassword: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91974-6
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
