id: system_settings_smbd_disable
title: Disable Server Message Block Sharing
discussion: |
  Support for Server Message Block (SMB) file sharing is non-essential and _MUST_ be disabled.

  The information system _MUST_ be configured to provide only essential capabilities.
check: |
  /bin/launchctl print-disabled system | /usr/bin/grep -c '"com.apple.smbd" => disabled'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /bin/launchctl disable system/com.apple.smbd
  ----
  The system may need to be restarted for the update to take effect.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-3
      - AC-17
    800-53r4:
      - AC-3
    800-171r2:
      - 3.1.1
      - 3.1.2
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91979-5
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.3.3.3 (level 1)
          controls v8:
            - 4.1
            - 4.8
            - 5.4
