id: system_settings_wifi_menu_enable
title: Enable Wifi Menu
discussion: |
  The WiFi menu _MUST_ be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
  .objectForKey('WiFi').js
  EOS
result: 18
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - N/A
    800-53r4:
      - N/A
    800-171r2:
      - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.controlcenter:
    WiFi: 18
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-92000-9
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - 2.4.1 (level 1)
          controls v8:
            - 4.8
            - 12.6
