id: system_settings_loginwindow_loginwindowtext_enable
title: Configure Login Window to Show A Custom Message
discussion: "The login window _MUST_ be configured to show a custom access warning message. \n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
  .objectForKey('LoginwindowText').js
  EOS
result:
  string: $ODV
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - $OS_VALUE
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
odv:
  hint: Organization's approved message.
  recommended: Center for Internet Security Test Message
  cis_lvl1: Center for Internet Security Test Message
  cis_lvl2: Center for Internet Security Test Message
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.loginwindow:
    LoginwindowText: $ODV
os_specifics:
  '13.0':
    references:
      cce:
        - CCE-91964-7
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 2.10.3 (level 1)
        controls v8:
          - 4.1
