id: system_settings_firewall_stealth_mode_enable
title: Enable Firewall Stealth Mode
discussion: "Firewall Stealth Mode _MUST_ be enabled. \n\nWhen stealth mode is enabled, the Mac will not respond to any probing requests, and only requests from authorized applications will still be authorized.\n\n[IMPORTANT]\n====\nEnabling firewall stealth mode may prevent certain remote mechanisms used for maintenance and compliance scanning from properly functioning. Information System Security Officers (ISSOs) are advised to first fully weigh the potential risks posed to their organization before opting not to enable stealth mode.\n====\n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.security.firewall')\
  .objectForKey('EnableStealthMode').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    cci:
      - None
  nist:
    800-53r5:
      - CM-7
      - CM-7(1)
      - SC-7(16)
      - SC-7
    800-53r4:
      - SC-7
      - CM-7
      - CM-7(1)
      - SC-7(16)
    800-171r2:
      - 3.4.6
      - 3.13.1
      - 3.13.2
      - 3.13.5
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.security.firewall:
    EnableStealthMode: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91949-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.2.2 (level 1)
          controls v8:
            - 4.1
            - 4.5
            - 4.8
