id: system_settings_time_machine_encrypted_configure
title: Ensure Time Machine Volumes are Encrypted
discussion: |
  Time Machine volumes _MUST_ be encrypted.
references:
  nist:
    cce:
      macos_26:
        - CCE-95410-7
      macos_15:
        - CCE-94403-3
      macos_14:
        - CCE-92998-4
  cis:
    benchmark:
      macos_26:
        - 2.3.4.2 (level 1)
      macos_15:
        - 2.3.4.2 (level 1)
      macos_14:
        - 2.3.4.2 (level 1)
    controls_v8:
      - 3.6
      - 3.11
      - 11.3
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    '14.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    enforcement_info:
      check:
        shell: /usr/bin/sudo /usr/bin/defaults read /Library/Preferences/com.apple.TimeMachine.plist | grep -c NotEncrypted
        result:
          integer: 0
      fix:
        additional_info: |-
          . Go to System Settings -> Time Machine
          . Click *Select Disk*
          . Select existing Backup Disk under *Available Disks*
          . Click *Encrypt Backups*
          . Click *Use Disk*
tags:
  - cisv8
