id: system_settings_external_intelligence_disable
title: Disable External Intelligence Integrations
discussion: |
  Integration with external intelligence systems _MUST_ be disabled unless approved by the organization. Disabling external intelligence integration will mitigate the risk of data being sent to unapproved third party.

  The information system _MUST_ be configured to provide only essential capabilities.
references:
  nist:
    cce:
      macos_26:
        - CCE-95365-3
      macos_15:
        - CCE-94523-8
    800-53r5:
      - AC-20
      - CM-7
      - CM-7(1)
    800-171r3:
      - 03.01.20
      - 03.04.06
  disa:
    cci:
      - CCI-000381
    srg:
      - SRG-OS-000095-GPOS-00049
    cmmc:
      - AC.L1-3.1.20
      - CM.L2-3.4.6
      - CM.L2-3.4.7
  cis:
    benchmark:
      macos_26:
        - 2.5.1.1 (level 1)
      macos_15:
        - 2.5.1.1 (level 1)
    controls_v8:
      - 4.1
      - 4.8
      - 15.3
platforms:
  macOS:
    '26.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    '15.0':
      benchmarks:
        - name: cis_lvl1
        - name: cis_lvl2
    enforcement_info:
      check:
        shell: |-
          /usr/bin/osascript -l JavaScript << EOS
          $.NSUserDefaults.alloc.initWithSuiteName('com.apple.applicationaccess')\
          .objectForKey('allowExternalIntelligenceIntegrations').js
          EOS
        result:
          string: 'false'
    introduced: '15.2'
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cnssi-1253_moderate
  - cmmc_lvl1
  - cmmc_lvl2
mobileconfig_info:
  - PayloadType: com.apple.applicationaccess
    PayloadContent:
      - allowExternalIntelligenceIntegrations: false
