id: system_settings_handoff_disable
title: Disable Handoff
discussion: "Handoff _MUST_ be disabled. \n\nHandoff allows you to continue working on a document or project when the user switches from one Apple device to another. Disabling Handoff prevents data transfers to unauthorized devices.\n"
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - CCI-000366
      - CCI-000370
      - CCI-000381
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
    srg:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-3
      - AC-20
      - CM-7
      - CM-7(1)
    800-171r2:
      - N/A
    800-53r4:
      - None
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl2_byod
  - cis_lvl2_enterprise
  - cisv8
  - stig
severity: low
supervised: false
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowActivityContinuation: false
os_specifics:
  iOS:
    '16.0':
      references:
        disa:
          disa_stig:
            - AIOS-16-010800
          srg:
            - None
          sfr:
            - 'FMT_SMF_EXT.1.1 #47'
        nist:
          cce:
            - N/A
        cis:
          benchmark:
            - 2.2.1.11 (level 2 - End-User Owned Devices)
            - 3.2.1.24 (level 2 - Institutionally-Owned Devices)
          controls v8:
            - 3.3
