id: system_settings_download_software_update_enforce
title: Enforce Software Update Downloads Updates Automatically using DDM.
discussion: |
  Software Update _MUST_ be configured to enforce automatic downloads of updates from Apple and that the user cannot modify the setting within System Settings.
check: |
  /usr/bin/plutil -convert json /var/db/softwareupdate/SoftwareUpdateDDMStatePersistence.plist -o - | /usr/bin/jq --raw-output .'SUCorePersistedStatePolicyFields.SUCoreDDMDeclarationGlobalSettings.automaticallyDownload' 
result:
  integer: 1
fix: |
  This is implemented by Declarative Device Management (DDM).
references:
  cce:
    - CCE-95403-2
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r3:
    - N/A
  cis:
    benchmark:
      - N/A
    controls v8:
      - 7.3
      - 7.4
macOS:
  - '26.0'
tags:
  - cisv8
  - ddm
mobileconfig: false
mobileconfig_info:
ddm_info:
  declarationtype: com.apple.configuration.softwareupdate.settings
  ddm_key: AutomaticActions
  ddm_value: 
    Download: AlwaysOn