id: system_settings_siri_listen_disable
title: Ensure Siri Listen For is Disabled
discussion: |
  Siri has the ability to listen for "Hey Siri" or "Siri". Listen for _MUST_ be disabled.
references:
  nist:
    cce:
      macos_26:
        - CCE-95399-2
      macos_15:
        - CCE-94392-8
      macos_14:
        - CCE-93022-2
  cis:
    controls_v8:
      - 4.1
      - 4.8
platforms:
  macOS:
    '26.0': {}
    '15.0': {}
    '14.0': {}
    enforcement_info:
      check:
        shell: |-
          /usr/bin/sudo /usr/bin/osascript -l JavaScript << EOS
          $.NSUserDefaults.alloc.initWithSuiteName('com.apple.Siri')\
          .objectForKey('VoiceTriggerUserEnabled').js
          EOS
        result:
          string: 'false'
    introduced: '-1'
tags:
  - cisv8
mobileconfig_info:
  - PayloadType: com.apple.Siri
    PayloadContent:
      - VoiceTriggerUserEnabled: false
