id: system_settings_firewall_enable
title: Enable macOS Application Firewall
discussion: "The macOS Application Firewall is the built-in firewall that comes with macOS, and it _MUST_ be enabled. \n\nWhen the macOS Application Firewall is enabled, the flow of information within the information system and between interconnected systems will be controlled by approved authorizations.\n"
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.security.firewall')\
  .objectForKey('EnableFirewall').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-4
      - SC-7(12)
      - CM-7
      - CM-7(1)
      - SC-7
    800-53r4:
      - AC-4
      - AC-6(1)
      - AC-19
      - SC-7
      - CM-7
      - CM-7(1)
      - SC-7(12)
    800-171r2:
      - 3.1.3
      - 3.1.5
      - 3.1.18
      - 3.4.6
      - 3.13.1
      - 3.13.2
      - 3.13.5
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.security.firewall:
    EnableFirewall: true
os_specifics:
  macOS:
    '13.0':
      references:
        cce:
          - CCE-91948-0
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 2.2.1 (level 1)
          controls v8:
            - 4.1
            - 4.5
            - 13.1
