id: audit_folder_owner_configure
title: Configure Audit Log Folders to be Owned by Root
discussion: $OS_VALUE
check: |
  /bin/ls -dn $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{print $3}'
result: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/chown root $(/usr/bin/awk -F : '/^dir/{print $2}' /etc/security/audit_control)
  ----
references:
  disa:
    cci:
      - CCI-000162
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AU-9
    800-53r4:
      - AU-9
    800-171r2:
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85269-9
        disa_stig:
          - APPL-11-001013
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
      discussion: |
        Audit log files _MUST_ be owned by root.

        The audit service _MUST_ be configured to create log files with the correct ownership to prevent normal users from reading audit logs.

        Audit logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
    '10.15':
      references:
        cce:
          - CCE-84718-6
        disa_stig:
          - AOSX-15-001013
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
      discussion: |
        Audit log files _MUST_ be owned by root.

        The audit service _MUST_ be configured to create log files with the correct ownership to prevent normal users from reading audit logs.

        Audit logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
    '12.0':
      references:
        cce:
          - CCE-90870-7
        disa_stig:
          - APPL-12-001013
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
      discussion: |
        Audit log files _MUST_ be owned by root.

        The audit service _MUST_ be configured to create log files with the correct ownership to prevent normal users from reading audit logs.

        Audit logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
    '13.0':
      references:
        cce:
          - CCE-91726-0
        disa_stig:
          - APPL-13-001013
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
      discussion: |
        Audit log folders _MUST_ be owned by root.

        The audit service _MUST_ be configured to create log folders with the correct ownership to prevent normal users from reading audit logs.

        Audit logs contain sensitive data about the system and users. If log folders are set to only be readable and writable by system administrators, the risk is mitigated.
