id: audit_flags_fm_configure
title: $OS_VALUE
discussion: $OS_VALUE
check: $OS_VALUE
result: 1
fix: $OS_VALUE
references:
  disa:
    cci:
      - CCI-000172
      - CCI-001814
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-2(12)
      - AU-12
      - AU-2
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-53r4:
      - AU-2
      - AU-12
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-171r2:
      - 3.3.1
      - 3.3.2
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - stig
  - 800-53r5_moderate
  - 800-53r5_low
  - 800-171
  - cisv8
  - 800-53r5_privacy
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_high
  - cis_lvl2
  - cnssi-1253
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85264-0
        disa_stig:
          - APPL-11-001020
        srg:
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: "The audit system _MUST_ be configured to record enforcement actions of failed attempts to modify file attributes (fm). \n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to modify a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
      title: Configure System to Audit All Failed Change of Object Attributes
      check: |
        /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fm'
      fix: |
        [source,bash]
        ----
        /usr/bin/grep -qE "^flags.*-fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fm/' /etc/security/audit_control;/usr/sbin/audit -s
        ----
    '10.15':
      references:
        cce:
          - CCE-84715-2
        disa_stig:
          - AOSX-15-001020
        srg:
          - SRG-OS-000064-GPOS-00033
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
        sfr:
          - N/A
        cis:
          benchmark:
            - N/A
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: "The audit system _MUST_ be configured to record enforcement actions of failed attempts to modify file attributes (fm). \n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to modify a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
      title: Configure System to Audit All Failed Change of Object Attributes
      check: |
        /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fm'
      fix: |
        [source,bash]
        ----
        /usr/bin/grep -qE "^flags.*-fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fm/' /etc/security/audit_control;/usr/sbin/audit -s
        ----
    '12.0':
      references:
        cce:
          - CCE-91086-9
        disa_stig:
          - APPL-12-001020
        srg:
          - SRG-OS-000064-GPOS-00033
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
        sfr:
          - N/A
      discussion: "The audit system _MUST_ be configured to record enforcement actions of attempts to modify file attributes (fm). \n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., modifications to a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions attempts to modify a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
      title: Configure System to Audit All Changes of Object Attributes
      check: |
        /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '^fm'
      fix: |
        [source,bash]
        ----
        /usr/bin/grep -qE "^flags.*fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,fm/' /etc/security/audit_control;/usr/sbin/audit -s
        ----
    '13.0':
      references:
        cce:
          - CCE-91720-3
        disa_stig:
          - APPL-13-001020
        srg:
          - SRG-OS-000064-GPOS-00033
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
        sfr:
          - N/A
      discussion: "The audit system _MUST_ be configured to record enforcement actions of attempts to modify file attributes (fm). \n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., modifications to a file by applying file permissions).\n\nThis configuration ensures that audit lists include events in which enforcement actions attempts to modify a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
      title: Configure System to Audit All Changes of Object Attributes
      check: |
        /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '^fm'
      fix: |
        [source,bash]
        ----
        /usr/bin/grep -qE "^flags.*fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,fm/' /etc/security/audit_control;/usr/sbin/audit -s
        ----
