id: audit_flags_fw_configure
title: Configure System to Audit All Failed Write Actions on the System
discussion: $OS_VALUE
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fw'
result: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-fw" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fw/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  disa:
    cci:
      - CCI-000162
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-2(12)
      - AU-12
      - AU-2
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-53r4:
      - AU-2
      - AU-12
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-171r2:
      - 3.3.1
      - 3.3.2
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_privacy
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253
  - cis_lvl2
  - cisv8
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        disa:
          disa_stig:
            - APPL-11-001020
          srg:
            - SRG-OS-000365-GPOS-00152
            - SRG-OS-000458-GPOS-00203
            - SRG-OS-000461-GPOS-00205
            - SRG-OS-000463-GPOS-00207
            - SRG-OS-000465-GPOS-00209
            - SRG-OS-000466-GPOS-00210
            - SRG-OS-000467-GPOS-00211
            - SRG-OS-000468-GPOS-00212
            - SRG-OS-000474-GPOS-00219
            - SRG-OS-000057-GPOS-00027
          sfr:
            - N/A
        nist:
          cce:
            - CCE-85266-5
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: "The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed file write (-fw) attempts.\n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using access restrictions (e.g., denying users access to edit a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to change a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
    '10.15':
      references:
        disa:
          disa_stig:
            - AOSX-15-001020
          srg:
            - SRG-OS-000064-GPOS-00033
            - SRG-OS-000365-GPOS-00152
            - SRG-OS-000458-GPOS-00203
            - SRG-OS-000461-GPOS-00205
            - SRG-OS-000463-GPOS-00207
            - SRG-OS-000465-GPOS-00209
            - SRG-OS-000466-GPOS-00210
            - SRG-OS-000467-GPOS-00211
            - SRG-OS-000468-GPOS-00212
            - SRG-OS-000474-GPOS-00219
          sfr:
            - N/A
        nist:
          cce:
            - CCE-84714-5
        cis:
          benchmark:
            - N/A
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: "The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed file write (-fw) attempts.\n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using access restrictions (e.g., denying users access to edit a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to change a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
    '12.0':
      references:
        disa:
          disa_stig:
            - APPL-12-001020
          srg:
            - SRG-OS-000064-GPOS-00033
            - SRG-OS-000365-GPOS-00152
            - SRG-OS-000458-GPOS-00203
            - SRG-OS-000461-GPOS-00205
            - SRG-OS-000463-GPOS-00207
            - SRG-OS-000465-GPOS-00209
            - SRG-OS-000466-GPOS-00210
            - SRG-OS-000467-GPOS-00211
            - SRG-OS-000468-GPOS-00212
            - SRG-OS-000474-GPOS-00219
          sfr:
            - N/A
        nist:
          cce:
            - CCE-90867-3
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: "The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed file write (-fw) attempts.\n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using access restrictions (e.g., denying users access to edit a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to change a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
    '13.0':
      references:
        disa:
          disa_stig:
            - APPL-13-001020
          srg:
            - SRG-OS-000064-GPOS-00033
            - SRG-OS-000365-GPOS-00152
            - SRG-OS-000458-GPOS-00203
            - SRG-OS-000461-GPOS-00205
            - SRG-OS-000463-GPOS-00207
            - SRG-OS-000465-GPOS-00209
            - SRG-OS-000466-GPOS-00210
            - SRG-OS-000467-GPOS-00211
            - SRG-OS-000468-GPOS-00212
            - SRG-OS-000474-GPOS-00219
          sfr:
            - N/A
        nist:
          cce:
            - CCE-91723-7
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
      discussion: |
        The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed file write (-fw) attempts.

        Enforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using access restrictions (e.g., denying users access to edit a file by applying file permissions).

        This configuration ensures that audit lists include events in which enforcement actions prevent attempts to change a file.

        Without auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.
