id: audit_files_owner_configure
title: Configure Audit Log Files to be Owned by Root
discussion: |
  Audit log files _MUST_ be owned by root.

  The audit service _MUST_ be configured to create log files with the correct ownership to prevent normal users from reading audit logs.

  Audit logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
check: "/bin/ls -n $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk\
  \ -F: '{print $2}') | /usr/bin/awk '{s+=$3} END {print s}'  \n"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/chown -R root $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')/*
  ----
references:
  cce: |-
    $OS_VALUE
  cci:
  - CCI-000162
  800-53r5:
  - AU-9
  800-53r4:
  - AU-9
  srg:
  - SRG-OS-000057-GPOS-00027
  disa_stig: |-
    $OS_VALUE
  800-171r2:
  - 3.3.8
  cis:
    benchmark:
    - 3.5 (level 1)
    controls v8:
    - 3.3
tags:
- 800-53r5_low
- 800-53r5_moderate
- 800-53r5_high
- 800-53r4_low
- 800-53r4_moderate
- 800-53r4_high
- 800-171
- cnssi-1253
- cis_lvl1
- cis_lvl2
- cisv8
- stig
severity: medium
mobileconfig: false
mobileconfig_info:
OS_specifics:
  macOS:
    '12':
      references:
        cce:
        - CCE-90860-8
        disa_stig:
        - APPL-12-001012
    '11':
      references:
        cce:
        - CCE-85260-8
        disa_stig:
        - APPL-11-001012
    '10.15':
      references:
        cce:
        - CCE-84710-3
        disa_stig:
        - AOSX-15-001012
