id: audit_flags_fd_configure
title: Configure System to Audit All Deletions of Object Attributes
discussion: "The audit system _MUST_ be configured to record enforcement actions of attempts to delete file attributes (fd). \n\n***Enforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to delete a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fd'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-fd" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fd/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  disa:
    cci:
      - CCI-000172
      - CCI-001814
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-2(12)
      - AU-12
      - AU-2
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-53r4:
      - AU-2
      - AU-12
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-171r2:
      - N/A
    cce:
      - $OS_VALUE
cis:
  benchmark:
    - N/A
  controls v8:
    - 3.14
    - 8.2
    - 8.5
tags:
  - 800-53r5_privacy
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - stig
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85264-0
        disa_stig:
          - APPL-11-001020
        srg:
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
          - SRG-OS-000057-GPOS-00027
    '12.0':
      references:
        cce:
          - CCE-90864-0
        disa_stig:
          - APPL-12-001020
        srg:
          - SRG-OS-000064-GPOS-00033
          - SRG-OS-000365-GPOS-00152
          - SRG-OS-000458-GPOS-00203
          - SRG-OS-000461-GPOS-00205
          - SRG-OS-000463-GPOS-00207
          - SRG-OS-000465-GPOS-00209
          - SRG-OS-000466-GPOS-00210
          - SRG-OS-000467-GPOS-00211
          - SRG-OS-000468-GPOS-00212
          - SRG-OS-000474-GPOS-00219
    '13.0':
      references:
        cce:
          - CCE-91719-5
        disa_stig:
          - N/A
        srg:
          - N/A
