id: audit_flags_fm_failed_configure
title: Configure System to Audit All Failed Change of Object Attributes
discussion: "The audit system _MUST_ be configured to record enforcement actions of failed attempts to modify file attributes (-fm). \n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized changes to configuration settings. One common and effective enforcement action method is using access restrictions (i.e., denying modifications to a file by applying file permissions). \n\nThis configuration ensures that audit lists include events in which enforcement actions prevent attempts to modify a file. \n\nWithout auditing the enforcement of access restrictions, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-fm'
result: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-fm" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-fm/' /etc/security/audit_control;/usr/sbin/audit -s
  ----
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AC-2(12)
      - AU-12
      - AU-2
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-53r4:
      - AU-2
      - AU-12
      - AU-9
      - CM-5(1)
      - MA-4(1)
    800-171r2:
      - 3.3.1
      - 3.3.2
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_privacy
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - cis_lvl2
  - cisv8
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '12.0':
      references:
        cce:
          - CCE-90865-7
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
    '13.0':
      references:
        cce:
          - CCE-91721-1
        disa_stig:
          - N/A
        srg:
          - N/A
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
