id: audit_control_group_configure
title: Configure Audit_Control Group to Wheel
discussion: |
  /etc/security/audit_control _MUST_ have the group set to wheel.
check: |
  /bin/ls -dn /etc/security/audit_control | /usr/bin/awk '{print $4}'
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/bin/chgrp wheel /etc/security/audit_control
  ----
references:
  cce:
    - $OS_VALUE
  800-53r5:
    - AU-9
  800-53r4:
    - AU-9
  srg:
    - $OS_VALUE
  disa_stig:
    - $OS_VALUE
  800-171r2:
    - N/A
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
  cci:
    - None
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  '11.0':
    references:
      cce:
        - CCE-85496-8
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 3.5 (level 1)
        controls v8:
          - 3.3
  '12.0':
    references:
      cce:
        - CCE-91089-3
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 3.5 (level 1)
        controls v8:
          - 3.3
  '13.0':
    references:
      cce:
        - CCE-91707-0
      disa_stig:
        - N/A
      srg:
        - N/A
      cis:
        benchmark:
          - 3.5 (level 1)
        controls v8:
          - 3.3
