id: audit_configure_capacity_notify
title: Configure Audit Capacity Warning
discussion: "The audit service _MUST_ be configured to notify the system administrator when the amount of free disk space remaining reaches an organization defined value. \n\nThis rule ensures that the system administrator is notified in advance that action is required to free up more disk space for audit logs.\n"
check: |
  /usr/bin/awk -F: '/^minfree/{print $2}' /etc/security/audit_control
result:
  integer: $ODV
fix: "[source,bash]\n----\n/usr/bin/sed -i.bak 's/.*minfree.*/minfree:$ODV/' /etc/security/audit_control; /usr/sbin/audit -s \n----\n"
references:
  disa:
    cci:
      - CCI-001855
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AU-5(1)
    800-53r4:
      - AU-5(1)
    cce:
      - $OS_VALUE
odv:
  hint: Percentage of free space.
  recommended: 25
  stig: 25
tags:
  - 800-53r5_high
  - 800-53r4_high
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85255-8
        disa_stig:
          - APPL-11-001030
        srg:
          - SRG-OS-000343-GPOS-00134
    '12.0':
      references:
        cce:
          - CCE-90855-8
        disa_stig:
          - APPL-12-001030
        srg:
          - SRG-OS-000343-GPOS-00134
    '13.0':
      references:
        cce:
          - CCE-91705-4
        disa_stig:
          - N/A
        srg:
          - N/A
