id: audit_flags_ex_configure
title: Configure System to Audit All Failed Program Execution on the System
discussion: "The audit system _MUST_ be configured to record enforcement actions of access restrictions, including failed program execute (-ex) attempts.\n\nEnforcement actions are the methods or mechanisms used to prevent unauthorized access and/or changes to configuration settings. One common and effective enforcement action method is using program execution restrictions (e.g., denying users access to execute certain processes). \n\nThis configuration ensures that audit lists include events in which program execution has failed. \nWithout auditing the enforcement of program execution, it is difficult to identify attempted attacks, as there is no audit trail available for forensic investigation.\n"
check: |
  /usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '\-ex'
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -qE "^flags.*-ex" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,-ex/' /etc/security/audit_control; /usr/sbin/audit -s
  ----
references:
  disa:
    cci:
      - N/A
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AC-2(12)
      - AU-12
      - AU-2
      - CM-5(1)
    800-53r4:
      - AU-2
      - AU-12
      - CM-5(1)
    800-171r2:
      - 3.3.1
      - 3.3.2
    cce:
      - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_privacy
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cis_lvl2
mobileconfig: false
mobileconfig_info: ''
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85263-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
    '12.0':
      references:
        cce:
          - CCE-90863-2
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
    '13.0':
      references:
        cce:
          - CCE-91718-7
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.2 (level 2)
          controls v8:
            - 3.14
            - 8.2
            - 8.5
