id: audit_acls_files_configure
title: Configure Audit Log Files to Not Contain Access Control Lists
discussion: |
  The audit log files _MUST_ not contain access control lists (ACLs).

  This rule ensures that audit information and audit files are configured to be readable and writable only by system administrators, thereby preventing unauthorized access, modification, and deletion of files.
check: |
  /bin/ls -le $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
result: 0
fix: |
  [source,bash]
  ----
  /bin/chmod -RN $(/usr/bin/awk -F: '/^dir/{print $2}' /etc/security/audit_control)
  ----
references:
  disa:
    cci:
      - CCI-000162
      - CCI-001314
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - SI-11
      - AU-9
    800-53r4:
      - AU-9
      - SI-11
    800-171r2:
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85251-7
        disa_stig:
          - APPL-11-000030
        srg:
          - SRG-OS-000057-GPOS-00027
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '10.15':
      references:
        cce:
          - CCE-84701-2
        disa_stig:
          - AOSX-15-000030
        srg:
          - SRG-OS-000057-GPOS-00027
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
    '12.0':
      references:
        cce:
          - CCE-90851-7
        disa_stig:
          - APPL-12-000030
        srg:
          - SRG-OS-000057-GPOS-00027
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91701-3
        disa_stig:
          - APPL-13-000030
        srg:
          - SRG-OS-000057-GPOS-00027
          - SRG-OS-000206-GPOS-00084
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
