id: audit_settings_failure_notify
title: Configure Audit Failure Notification
discussion: $OS_VALUE
check: |
  /usr/bin/grep -c "logger -s -p" /etc/security/audit_warn
result: 1
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/logger -p/logger -s -p/' /etc/security/audit_warn; /usr/sbin/audit -s
  ----
references:
  disa:
    cci:
      - CCI-001858
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AU-5(2)
      - AU-5
    800-53r4:
      - AU-5
      - AU-5(2)
    800-171r2:
      - 3.3.4
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r4_high
  - 800-53r5_high
  - 800-171
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85273-1
        disa_stig:
          - APPL-11-001031
        srg:
          - SRG-OS-000344-GPOS-00135
        sfr:
          - N/A
      discussion: "The audit service _MUST_ be configured to immediately print messages to the console or email administrator users when an auditing failure occurs. \n\nIt is critical for the appropriate personnel to be made aware immediately if a system is at risk of failing to process audit logs as required. Without a real-time alert, security personnel may be unaware of a potentially harmful failure in the auditing system's capability, and system operation may be adversely affected. \n"
    '10.15':
      references:
        cce:
          - CCE-84720-2
        disa_stig:
          - AOSX-15-001031
        srg:
          - SRG-OS-000344-GPOS-00135
        sfr:
          - N/A
      discussion: "The audit service _MUST_ be configured to immediately print messages to the console or email administrator users when an auditing failure occurs. \n\nIt is critical for the appropriate personnel to be made aware immediately if a system is at risk of failing to process audit logs as required. Without a real-time alert, security personnel may be unaware of a potentially harmful failure in the auditing system's capability, and system operation may be adversely affected. \n"
    '12.0':
      references:
        cce:
          - CCE-90876-4
        disa_stig:
          - APPL-12-001031
        srg:
          - SRG-OS-000344-GPOS-00135
        sfr:
          - N/A
      discussion: "The audit service _MUST_ be configured to immediately print messages to the console or email administrator users when an auditing failure occurs. \n\nIt is critical for the appropriate personnel to be made aware immediately if a system is at risk of failing to process audit logs as required. Without a real-time alert, security personnel may be unaware of a potentially harmful failure in the auditing system's capability, and system operation may be adversely affected. \n"
    '13.0':
      references:
        cce:
          - CCE-91732-8
        disa_stig:
          - APPL-13-001031
        srg:
          - SRG-OS-000344-GPOS-00135
        sfr:
          - N/A
      discussion: |
        The audit service _MUST_ be configured to immediately print messages to the console or email administrator users when an auditing failure occurs.

        It is critical for the appropriate personnel to be made aware immediately if a system is at risk of failing to process audit logs as required. Without a real-time alert, security personnel may be unaware of a potentially harmful failure in the auditing system's capability, and system operation may be adversely affected.
