id: audit_control_owner_configure
title: Configure Audit_Control Owner to Root
discussion: |
  /etc/security/audit_control _MUST_ have the owner set to root.
check: |
  /bin/ls -dn /etc/security/audit_control | /usr/bin/awk '{print $3}'
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/chown root /etc/security/audit_control
  ----
references:
  disa:
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    cci:
      - None
  nist:
    800-53r5:
      - AU-9
    800-53r4:
      - AU-9
    800-171r2:
      - N/A
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85498-4
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '12.0':
      references:
        cce:
          - CCE-91091-9
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91709-6
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
