id: audit_files_group_configure
title: Configure Audit Log Files Group to Wheel
discussion: "Audit log files _MUST_ have the group set to wheel.\n\nThe audit service _MUST_ be configured to create log files with the correct group ownership to prevent normal users from reading audit logs. \n\nAudit logs contain sensitive data about the system and users. If log files are set to be readable and writable only by system administrators, the risk is mitigated.\n"
check: |
  /bin/ls -n $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{s+=$4} END {print s}'
result: 0
fix: |
  [source,bash]
  ----
  /usr/bin/chgrp -R wheel $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')/*
  ----
references:
  disa:
    cci:
      - CCI-000162
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
    sfr:
      - $OS_VALUE
  nist:
    cce:
      - $OS_VALUE
    800-53r5:
      - AU-9
    800-53r4:
      - AU-9
    800-171r2:
      - 3.3.8
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - cnssi-1253
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - stig
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85258-2
        disa_stig:
          - APPL-11-001014
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '10.15':
      references:
        cce:
          - CCE-84709-5
        disa_stig:
          - AOSX-15-001014
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
    '12.0':
      references:
        cce:
          - CCE-90858-2
        disa_stig:
          - APPL-12-001014
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91712-0
        disa_stig:
          - APPL-13-001014
        srg:
          - SRG-OS-000057-GPOS-00027
        sfr:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
