id: audit_folders_mode_configure
title: Configure Audit Log Folders to Mode 700 or Less Permissive
discussion: "The audit log folder _MUST_ be configured to mode 700 or less permissive so that only the root user is able to read, write, and execute changes to folders. \n\nBecause audit logs contain sensitive data about the system and users, the audit service _MUST_ be configured to mode 700 or less permissive; thereby preventing normal users from reading, modifying or deleting audit logs. \n"
check: |
  /usr/bin/stat -f %A $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
result:
  integer: 700
fix: |
  [source,bash]
  ----
  /bin/chmod 700 $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
  ----
references:
  disa:
    cci:
      - CCI-000162
      - CCI-000163
      - CCI-000164
    srg:
      - $OS_VALUE
    disa_stig:
      - $OS_VALUE
  nist:
    800-53r5:
      - AU-9
    800-53r4:
      - AU-9
    800-171r2:
      - 3.3.8
  cce:
    - $OS_VALUE
  cis:
    benchmark:
      - $OS_VALUE
    controls v8:
      - $OS_VALUE
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - 800-171
  - stig
  - cis_lvl1
  - cis_lvl2
severity: medium
mobileconfig: false
mobileconfig_info: null
os_specifics:
  macOS:
    '11.0':
      references:
        cce:
          - CCE-85270-7
        disa_stig:
          - APPL-11-001017
        srg:
          - SRG-OS-000058-GPOS-00028
          - SRG-OS-000059-GPOS-00029
          - SRG-OS-000057-GPOS-00027
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '12.0':
      references:
        cce:
          - CCE-90871-5
        disa_stig:
          - APPL-12-001017
        srg:
          - SRG-OS-000057-GPOS-00027
          - SRG-OS-000058-GPOS-00028
          - SRG-OS-000059-GPOS-00029
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
    '13.0':
      references:
        cce:
          - CCE-91727-8
        disa_stig:
          - N/A
        srg:
          - N/A
        cis:
          benchmark:
            - 3.5 (level 1)
          controls v8:
            - 3.3
