name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint the yams
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/workflows/.yamllint
      - name: verify yams schema
        run:
          pip install cerberus
          ./includes/check_mscp_schema.py $(git ls-files "*.yaml")
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}