name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Github Variables
        run: echo "${{ toJson(github) }}"
      - uses: actions/checkout@v3
      - name: lint the yams
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/workflows/.yamllint
      - name: verify yams schema
        run: |
          pip install -q cerberus
          ./includes/check_mscp_schema.py $(git ls-files "*.yaml")
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} Commit from: ${{ github.event.head_commit.author.username }} - ${{ github.event.head_commit.message }}"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}